# Generated by Django 4.1.3 on 2022-12-13 12:35

import django.core.validators
from django.db import migrations, models
import driving_school.booking.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), driving_school.booking.validators.validate_string_alphanumeric])),
                ('last_name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), driving_school.booking.validators.validate_string_alphanumeric])),
                ('week_schedule', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=20)),
                ('text_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
