# Generated by Django 4.1.3 on 2022-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='hour_schedule',
            field=models.CharField(choices=[('nine', '9 AM'), ('ten', '10 AM'), ('eleven', '11 AM'), ('twelve', '12 PM'), ('thirteen', '13 PM'), ('fourteen', '14 PM'), ('fifteen', '15 PM'), ('sixteen', '16 PM'), ('seventeen', '17 PM')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
