# Generated by Django 4.1.3 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmodel_hour_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
