# Generated by Django 4.1.3 on 2022-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField()),
                ('description_practice', models.TextField(blank=True, null=True)),
                ('description_theory', models.TextField(blank=True, null=True)),
                ('description_test', models.TextField(blank=True, null=True)),
                ('description_not_included', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
